/* tslint:disable */
/* eslint-disable */
/**
 * Modality REST API
 * Modality REST API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@auxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventCoordinate
 */
export interface EventCoordinate {
    /**
     * 
     * @type {Array<number>}
     * @memberof EventCoordinate
     */
    opaqueEventId?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof EventCoordinate
     */
    timelineId?: string;
}

/**
 * Check if a given object implements the EventCoordinate interface.
 */
export function instanceOfEventCoordinate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventCoordinateFromJSON(json: any): EventCoordinate {
    return EventCoordinateFromJSONTyped(json, false);
}

export function EventCoordinateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCoordinate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'opaqueEventId': !exists(json, 'opaque_event_id') ? undefined : json['opaque_event_id'],
        'timelineId': !exists(json, 'timeline_id') ? undefined : json['timeline_id'],
    };
}

export function EventCoordinateToJSON(value?: EventCoordinate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'opaque_event_id': value.opaqueEventId,
        'timeline_id': value.timelineId,
    };
}

