/* tslint:disable */
/* eslint-disable */
/**
 * Modality REST API
 * Modality REST API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@auxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaggedNonFiniteFloat
 */
export interface TaggedNonFiniteFloat {
    /**
     * 
     * @type {string}
     * @memberof TaggedNonFiniteFloat
     */
    nonFiniteFloat?: TaggedNonFiniteFloatNonFiniteFloatEnum;
}


/**
 * @export
 */
export const TaggedNonFiniteFloatNonFiniteFloatEnum = {
    NaN: 'NaN',
    MinusNaN: '-NaN',
    Infinity: 'Infinity',
    MinusInfinity: '-Infinity'
} as const;
export type TaggedNonFiniteFloatNonFiniteFloatEnum = typeof TaggedNonFiniteFloatNonFiniteFloatEnum[keyof typeof TaggedNonFiniteFloatNonFiniteFloatEnum];


/**
 * Check if a given object implements the TaggedNonFiniteFloat interface.
 */
export function instanceOfTaggedNonFiniteFloat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nonFiniteFloat" in value;

    return isInstance;
}

export function TaggedNonFiniteFloatFromJSON(json: any): TaggedNonFiniteFloat {
    return TaggedNonFiniteFloatFromJSONTyped(json, false);
}

export function TaggedNonFiniteFloatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaggedNonFiniteFloat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nonFiniteFloat': !exists(json, 'NonFiniteFloat') ? undefined : json['NonFiniteFloat'],
    };
}

export function TaggedNonFiniteFloatToJSON(value?: TaggedNonFiniteFloat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NonFiniteFloat': value.nonFiniteFloat,
    };
}

