/* tslint:disable */
/* eslint-disable */
/**
 * Modality REST API
 * Modality REST API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@auxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaggedBigInt
 */
export interface TaggedBigInt {
    /**
     * 
     * @type {string}
     * @memberof TaggedBigInt
     */
    bigInt?: string;
}

/**
 * Check if a given object implements the TaggedBigInt interface.
 */
export function instanceOfTaggedBigInt(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bigInt" in value;

    return isInstance;
}

export function TaggedBigIntFromJSON(json: any): TaggedBigInt {
    return TaggedBigIntFromJSONTyped(json, false);
}

export function TaggedBigIntFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaggedBigInt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bigInt': !exists(json, 'BigInt') ? undefined : json['BigInt'],
    };
}

export function TaggedBigIntToJSON(value?: TaggedBigInt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BigInt': value.bigInt,
    };
}

