/* tslint:disable */
/* eslint-disable */
/**
 * Modality REST API
 * Modality REST API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@auxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaggedLogicalTime
 */
export interface TaggedLogicalTime {
    /**
     * 
     * @type {Array<number>}
     * @memberof TaggedLogicalTime
     */
    logicalTime?: Array<number>;
}

/**
 * Check if a given object implements the TaggedLogicalTime interface.
 */
export function instanceOfTaggedLogicalTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "logicalTime" in value;

    return isInstance;
}

export function TaggedLogicalTimeFromJSON(json: any): TaggedLogicalTime {
    return TaggedLogicalTimeFromJSONTyped(json, false);
}

export function TaggedLogicalTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaggedLogicalTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logicalTime': !exists(json, 'LogicalTime') ? undefined : json['LogicalTime'],
    };
}

export function TaggedLogicalTimeToJSON(value?: TaggedLogicalTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LogicalTime': value.logicalTime,
    };
}

