/* tslint:disable */
/* eslint-disable */
/**
 * Modality REST API
 * Modality REST API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@auxon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttrVal } from './AttrVal';
import {
    AttrValFromJSON,
    AttrValFromJSONTyped,
    AttrValToJSON,
} from './AttrVal';

/**
 * 
 * @export
 * @interface Timeline
 */
export interface Timeline {
    /**
     * 
     * @type {{ [key: string]: AttrVal; }}
     * @memberof Timeline
     */
    attributes: { [key: string]: AttrVal; };
    /**
     * 
     * @type {string}
     * @memberof Timeline
     */
    id: string;
}

/**
 * Check if a given object implements the Timeline interface.
 */
export function instanceOfTimeline(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function TimelineFromJSON(json: any): Timeline {
    return TimelineFromJSONTyped(json, false);
}

export function TimelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timeline {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': (mapValues(json['attributes'], AttrValFromJSON)),
        'id': json['id'],
    };
}

export function TimelineToJSON(value?: Timeline | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': (mapValues(value.attributes, AttrValToJSON)),
        'id': value.id,
    };
}

