name: Publish to VSCode Extension Marketplace

on: [workflow_dispatch]

jobs:
  publish:
    name: Publish
    timeout-minutes: 150
    runs-on: ubuntu-20.04
    environment: publish

    steps:
      - name: Install vsce tool
        run: npm install -g @vscode/vsce

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: |
          cd vscode
          npm install
          vsce package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: vscode/*.vsix
          retention-days: 2
          if-no-files-found: error

      - name: Publish to marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          set -ex
          cd vscode
          vsce publish
